---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: app
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: db
        image: gopibrahmaiah/library:dbimage-v1
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: app
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-library
  template:
    metadata:
      labels:
        app: auth-library
    spec:
      containers:
      - name: auth-service
        image: gopibrahmaiah/library:authimage
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: auth-library
  ports:
  - port: 80
    targetPort: 5001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-library
  template:
    metadata:
      labels:
        app: book-library
    spec:
      containers:
      - name: book-service
        image: gopibrahmaiah/library:bookimage
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: book-library
  ports:
  - port: 80
    targetPort: 5002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrow
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: borrow-library
  template:
    metadata:
      labels:
        app: borrow-library
    spec:
      containers:
      - name: borrow-service
        image: gopibrahmaiah/library:borrowimage
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: borrow-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: borrow-library
  ports:
  - port: 80
    targetPort: 5003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-library
  template:
    metadata:
      labels:
        app: app-library
    spec:
      containers:
      - name: app-service
        image: gopibrahmaiah/library:app
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app: app-library
  ports:
  - port: 80
    targetPort: 5000
