---
kind: Deployment
metadata:
  name: mydp
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library
    template:
      metadata:
        Labels:
          app: library
    spec:
      containers:
        - name: auth_service
          image: gopibrahmaiah/library:authimage
          ports:
            -containerPort: 5001

  
